// Biometry-gated storage for the sudo secret (see docs/SPEC-mobile-cloud-sudo.md).
//
// The secret is a 32-byte hex string generated by the sidecar at enrollment.
// It is stored as a generic keychain item whose access control requires the
// *currently enrolled* biometrics (Touch ID); reading it back triggers the
// system biometric prompt — the OS refuses to release the item without it.
// If biometric enrollment changes (new fingerprint added), the item becomes
// unreadable and the user re-enrolls, which is exactly the desired behavior.

const SERVICE: &str = "com.thoughts.sudo";
const ACCOUNT: &str = "sudo-secret";

#[cfg(target_os = "macos")]
mod platform {
    use super::{ACCOUNT, SERVICE};
    use security_framework::passwords::{
        delete_generic_password, get_generic_password, set_generic_password_options,
    };
    use security_framework::passwords_options::{AccessControlOptions, PasswordOptions};

    pub fn store_secret(secret_hex: &str) -> Result<(), String> {
        // Replace any previous enrollment.
        let _ = delete_generic_password(SERVICE, ACCOUNT);

        let mut options = PasswordOptions::new_generic_password(SERVICE, ACCOUNT);
        options.set_access_control_options(AccessControlOptions::BIOMETRY_CURRENT_SET);
        set_generic_password_options(secret_hex.as_bytes(), options).map_err(|e| e.to_string())
    }

    pub fn release_secret() -> Result<String, String> {
        // SecItemCopyMatching on an item with a biometry ACL shows the
        // Touch ID sheet and blocks until the user passes or cancels.
        let bytes = get_generic_password(SERVICE, ACCOUNT).map_err(|e| e.to_string())?;
        String::from_utf8(bytes).map_err(|e| e.to_string())
    }

    pub fn clear_secret() -> Result<(), String> {
        delete_generic_password(SERVICE, ACCOUNT).map_err(|e| e.to_string())
    }
}

#[cfg(not(target_os = "macos"))]
mod platform {
    pub fn store_secret(_secret_hex: &str) -> Result<(), String> {
        Err("sudo mode requires macOS (Touch ID)".into())
    }

    pub fn release_secret() -> Result<String, String> {
        Err("sudo mode requires macOS (Touch ID)".into())
    }

    pub fn clear_secret() -> Result<(), String> {
        Err("sudo mode requires macOS (Touch ID)".into())
    }
}

#[tauri::command]
pub fn sudo_store_secret(secret_hex: String) -> Result<(), String> {
    platform::store_secret(&secret_hex)
}

#[tauri::command]
pub async fn sudo_release_secret() -> Result<String, String> {
    // The biometric prompt blocks; keep it off the main thread.
    tauri::async_runtime::spawn_blocking(platform::release_secret)
        .await
        .map_err(|e| e.to_string())?
}

#[tauri::command]
pub fn sudo_clear_secret() -> Result<(), String> {
    platform::clear_secret()
}
